############################### MESSAGES ################################################
no_permission: "&cYou don't have permission to access this command!"
loot_message: "&aYou have claimed a LootChest!"
lootchest_looted: "&cThis LootChest is being looted by another player."
############################### OPTIONS #################################################
# Keeps LootChest until it's fully looted
full-loot: true
#########################################################################################